// Compile the JSON Schema to a standalone validator at build time.
// The generated code needs no runtime code generation, so it works under a strict Content Security Policy.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const Ajv2020 = require("ajv/dist/2020").default;
const addFormats = require("ajv-formats").default;
const standaloneCode = require("ajv/dist/standalone").default;

const schema = JSON.parse(readFileSync("src/schema/v0.1/player.json", "utf8"));

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  strictTypes: false,
  strictRequired: false,
  code: { source: true, esm: true, lines: true },
});
addFormats(ajv, { mode: "full", formats: ["date", "date-time"] });

const validate = ajv.compile(schema);
let code = standaloneCode(ajv, validate);

// Ajv emits require() calls for its runtime helpers, even in ESM mode. Convert them to imports.
const requires = [...new Set([...code.matchAll(/require\("([^"]+)"\)/g)].map((m) => m[1]))];
// Node gives module.exports as the default import of a CommonJS module. Bundlers such as Vite can give exports.default.
// __cjs returns the object that require() returns in both cases.
const imports = requires.flatMap((specifier, i) => {
  const name = `__runtime${i}`;
  code = code.replaceAll(`require("${specifier}")`, name);
  return [`import * as ${name}_ns from "${specifier}.js";`, `const ${name} = __cjs(${name}_ns);`];
});
const shim = `const __cjs = (ns) => (ns.default !== null && typeof ns.default === "object" ? ns.default : ns);`;
code = code.replace('"use strict";', `"use strict";\n${shim}\n${imports.join("\n")}`);

mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/validate-v0-1.js", `// Generated by scripts/compile-schema.mjs. Do not edit.\n${code}`);
writeFileSync(
  "src/generated/validate-v0-1.d.ts",
  `// Generated by scripts/compile-schema.mjs. Do not edit.
import type { ErrorObject } from "ajv";
declare const validate: ((data: unknown) => boolean) & { errors?: ErrorObject[] | null };
export default validate;
`,
);
console.log("Compiled src/generated/validate-v0-1.js");
